### ISSUE TITLE
can't find openvidu/openvidu-caddy-local source code

### ISSUE THREAD

**Issue by morya** [OpenVidu/openvidu-local-deployment#3]
wonderful project, and, where could I find the openvidu/openvidu-caddy-local source, thx

**Comment by pabloFuente** [comment]
Hello,

I am afraid that Docker image `openvidu/openvidu-caddy-local` is free-to-use, but its source files are not open source at the moment. The rest of the openvidu-local-deployment elements are open source and available to the public.
